"""create wordbooks and wordbook_words tables

Revision ID: 93f70c4a6a8d
Revises: aafab28b53c7
Create Date: 2025-11-12 13:26:35.468506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93f70c4a6a8d'
down_revision: Union[str, Sequence[str], None] = 'aafab28b53c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wordbooks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wordbooks_user_id'), 'wordbooks', ['user_id'], unique=False)
    op.create_table('wordbook_words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wordbook_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('custom_pronunciation', sa.String(length=100), nullable=True),
    sa.Column('custom_difficulty', sa.Integer(), nullable=True),
    sa.Column('custom_note', sa.Text(), nullable=True),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('incorrect_count', sa.Integer(), nullable=False),
    sa.Column('last_studied', sa.DateTime(), nullable=True),
    sa.Column('mastered', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wordbook_id'], ['wordbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wordbook_words_word_id'), 'wordbook_words', ['word_id'], unique=False)
    op.create_index(op.f('ix_wordbook_words_wordbook_id'), 'wordbook_words', ['wordbook_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wordbook_words_wordbook_id'), table_name='wordbook_words')
    op.drop_index(op.f('ix_wordbook_words_word_id'), table_name='wordbook_words')
    op.drop_table('wordbook_words')
    op.drop_index(op.f('ix_wordbooks_user_id'), table_name='wordbooks')
    op.drop_table('wordbooks')
    # ### end Alembic commands ###
