"""create words table

Revision ID: aafab28b53c7
Revises: 3dca96c2b00b
Create Date: 2025-11-12 13:05:06.038989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aafab28b53c7'
down_revision: Union[str, Sequence[str], None] = '3dca96c2b00b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('pronunciation', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('meanings', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('gpt_generated', sa.Boolean(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 5', name='check_difficulty_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_gpt_generated'), 'words', ['gpt_generated'], unique=False)
    op.create_index(op.f('ix_words_word'), 'words', ['word'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_words_word'), table_name='words')
    op.drop_index(op.f('ix_words_gpt_generated'), table_name='words')
    op.drop_table('words')
    # ### end Alembic commands ###
